# Generated by Django 4.0.3 on 2022-03-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(unique=True)),
                ('total_letters', models.PositiveIntegerField()),
                ('total_vowel_letters', models.PositiveIntegerField()),
                ('total_consonant_letters', models.PositiveIntegerField()),
                ('total_similar_letters', models.JSONField()),
                ('average_word_len', models.PositiveIntegerField()),
                ('top_three_words', models.JSONField()),
            ],
        ),
    ]
